import { useState } from "react";
import "../ProjectsGrid/ProjectsGrid.css";
import { DiJsBadge } from "react-icons/di";
import { FaReact, FaHtml5, FaCss3Alt, FaNodeJs, FaGitAlt, FaGithub } from "react-icons/fa";
import { SiTypescript, SiTailwindcss, SiMysql, SiPostgresql } from "react-icons/si";
import { VscVscode } from "react-icons/vsc";
import { RiNextjsFill } from "react-icons/ri";
import { BsArrowUpRight } from "react-icons/bs";
import { IoConstruct } from "react-icons/io5";
import { FiChevronLeft, FiChevronRight } from "react-icons/fi";
import { SiPrisma } from "react-icons/si";
import { useLanguage } from "../../context/useLanguage.js";
import theDevNews from "../../assets/the-dev-news.png"; import theDevNewsGif from "../../assets/the-dev-news.gif";
import boardTarefas from "../../assets/board-tarefas.png"; import boardTarefasGif from "../../assets/board-tarefas-gif.gif";
import landingPage from "../../assets/landing-page.png"; import landingPageGif from "../../assets/landing-page.gif";
import portfolio from "../../assets/portfolioWhite.png"; import portfolioDark from "../../assets/portfolioDark.png";
import jrlingeries from "../../assets/jr-lingeries.png"; import jrLingeriesGif from "../../assets/jr-lingeries-gif.gif"; import jrLingeriesGif2 from "../../assets/jr-lingeries-gif-2.gif";

const techStack=[{name:"HTML5",icon:<FaHtml5/>},{name:"CSS3",icon:<FaCss3Alt/>},{name:"JavaScript",icon:<DiJsBadge/>},{name:"TypeScript",icon:<SiTypescript/>},{name:"React",icon:<FaReact/>},{name:"Next.js",icon:<RiNextjsFill/>},{name:"Node.js",icon:<FaNodeJs/>},{name:"Tailwind CSS",icon:<SiTailwindcss/>},{name:"MySQL",icon:<SiMysql/>},{name:"PostgreSQL",icon:<SiPostgresql/>},{name:"Git",icon:<FaGitAlt/>},{name:"GitHub",icon:<FaGithub/>},{name:"VS Code",icon:<VscVscode/>}];
const projects=[
{title:"BLOG - The Dev News",description:"Uma landing page para o portal The Dev News, desenvolvida com HTML e CSS. O objetivo deste projeto é apresentar as notícias do universo da programação de forma atrativa, informativa e responsiva.",images:[theDevNews,theDevNewsGif],link:"https://github.com/DevDonov4n/RID-219930_Desafio2",technologies:[{name:"JavaScript",icon:<DiJsBadge/>},{name:"HTML",icon:<FaHtml5/>},{name:"CSS",icon:<FaCss3Alt/>}]},
{title:"Board de Tarefas",description:"Um projeto de board de tarefas desenvolvido com HTML, CSS e JavaScript, utilizando conceitos de Local Storage, mudança de estado e componentização.",images:[boardTarefas,boardTarefasGif],link:"https://github.com/DevDonov4n/RID-219930_Desafio3",technologies:[{name:"JavaScript",icon:<DiJsBadge/>},{name:"HTML",icon:<FaHtml5/>},{name:"CSS",icon:<FaCss3Alt/>}]},
{title:"Landing Page",description:"Uma landing page para a instituição DNC, desenvolvida com HTML, CSS e JavaScript. O objetivo deste projeto é montar a landing page com integração ao Sheet Monkey.",images:[landingPage,landingPageGif],link:"https://github.com/DevDonov4n/RID-219930_Desafio01",technologies:[{name:"HTML",icon:<FaHtml5/>},{name:"CSS",icon:<FaCss3Alt/>}]},
{title:"Portfólio Pessoal",description:"Portfólio pessoal desenvolvido para apresentar minha trajetória, habilidades e projetos na área de desenvolvimento de software, com uma interface moderna, responsiva e interativa.",images:[portfolio,portfolioDark],link:"https://github.com/DevDonov4n/Donovan-Bueno-Port",technologies:[{name:"React",icon:<FaReact/>},{name:"JavaScript",icon:<DiJsBadge/>},{name:"TypeScript",icon:<SiTypescript/>},{name:"HTML",icon:<FaHtml5/>},{name:"CSS",icon:<FaCss3Alt/>}]},
{title:"JR Lingeries",description:"Um e-commerce de roupas íntimas com login para clientes e dashboard para o responsável acompanhar leads, estoque e renda mensal arrecadada.",images:[jrlingeries,jrLingeriesGif,jrLingeriesGif2],link:"https://github.com/DevDonov4n/jr-lingeries",building:true,technologies:[{name:"TypeScript",icon:<SiTypescript/>},{name:"Next.js",icon:<RiNextjsFill/>},{name:"React",icon:<FaReact/>},{name:"Prisma",icon:<SiPrisma/>},{name:"MySQL",icon:<SiMysql/>},{name:"Node.JS",icon:<FaNodeJs/>}]}
];
const english=["A landing page for The Dev News portal, built with HTML and CSS to present programming news in an attractive, informative and responsive way.","A task board built with HTML, CSS and JavaScript, applying Local Storage, state changes and componentization concepts.","A DNC landing page built with HTML, CSS and JavaScript, with Sheet Monkey integration.","A personal portfolio built to showcase my journey, skills and software development projects through a modern, responsive and interactive interface.","An underwear e-commerce with customer login and a dashboard for tracking leads, inventory and monthly revenue."];

function ProjectCarousel({images,title}){const[currentImage,setCurrentImage]=useState(0);const[touchStart,setTouchStart]=useState(null);const previousImage=()=>{if(images.length>1)setCurrentImage(c=>c===0?images.length-1:c-1)};const nextImage=()=>{if(images.length>1)setCurrentImage(c=>c===images.length-1?0:c+1)};return <div className="project-carousel" onTouchStart={e=>setTouchStart(e.touches[0].clientX)} onTouchEnd={e=>{if(touchStart!==null&&images.length>1){const d=touchStart-e.changedTouches[0].clientX;if(Math.abs(d)>50)(d>0?nextImage:previousImage)()}setTouchStart(null)}}><img src={images[currentImage]} className="img-projects" alt={`Preview do projeto ${title}`}/>{images.length>1&&<><button type="button" className="carousel-arrow carousel-arrow-left" onClick={previousImage}><FiChevronLeft/></button><button type="button" className="carousel-arrow carousel-arrow-right" onClick={nextImage}><FiChevronRight/></button><div className="carousel-dots">{images.map((_,i)=><button type="button" key={i} className={`carousel-dot ${i===currentImage?"active":""}`} onClick={()=>setCurrentImage(i)} aria-label={`Imagem ${i+1}`}/>)}</div></>}</div>}
function TechStackCarousel(){const[isPaused,setIsPaused]=useState(false);const render=(duplicate=false)=><div className="tech-stack-track" aria-hidden={duplicate}>{techStack.map(t=><button type="button" className="tech-stack-item" key={`${t.name}-${duplicate}`} onClick={()=>setIsPaused(p=>!p)}><span className="tech-stack-icon">{t.icon}</span><span className="tech-stack-name">{t.name}</span></button>)}</div>;return <div className={`tech-stack-carousel ${isPaused?"is-paused":""}`}><div className="tech-stack-track-wrapper"><div className="tech-stack-track-group">{render()}{render(true)}</div></div></div>}
function ProjectsGrid(){const{language}=useLanguage();const ui=language==="en"?{title:"Developed Projects",intro:"Throughout my journey, I have been building projects with different technologies and putting my development knowledge into practice.",building:"In development",button:"View Project"}:{title:"Projetos Desenvolvidos",intro:"Em minha caminhada, venho realizando alguns projetos utilizando diferentes tecnologias e colocando em prática meus conhecimentos de desenvolvimento.",building:"Em desenvolvimento",button:"Ver Projeto"};return <section className="projects-section"><div className="projects-intro"><h1 id="projects-title">{ui.title}</h1><p id="projects-p">{ui.intro}</p></div><section className="tech-stack"><div className="tech-stack-header"><span className="tech-stack-line"/><h2 id="tech-stack-title">🚀 Tech Stack</h2></div><TechStackCarousel/></section><section className="projects"><div className="projects-grid">{projects.map((project,index)=><article className="card-projects" key={project.title}><ProjectCarousel images={project.images} title={project.title}/><h3 className="card-title">{language==="en"&&index===1?"Task Board":language==="en"&&index===3?"Personal Portfolio":project.title}</h3><p>{language==="en"?english[index]:project.description}</p><div className="language-tags">{project.building&&<span className="language-tag-building"><IoConstruct/> {ui.building}</span>}{project.technologies.map(t=><span className="language-tag" key={t.name}>{t.icon} {t.name}</span>)}</div><a href={project.link} target="_blank" rel="noopener noreferrer" className="card-btn">{ui.button} <BsArrowUpRight/></a></article>)}</div></section></section>}
export default ProjectsGrid;
